Qa.create(:question =>'こんにちは', :answer =>'a', :soundfile =>'https://s3.us-east-2.amazonaws.com/vocabrary-app/watashi-teijide-kaerimasu_1_1.mp3')
Qa.create(:question =>'い', :answer =>'i', :soundfile =>'https://s3.us-east-2.amazonaws.com/vocabrary-app/watashi-teijide-kaerimasu_1_2.mp3')
Qa.create(:question =>'う', :answer =>'u', :soundfile =>'https://s3.us-east-2.amazonaws.com/vocabrary-app/watashi-teijide-kaerimasu_1_3.mp3')
Qa.create(:question =>'え', :answer =>'e', :soundfile =>'https://s3.us-east-2.amazonaws.com/vocabrary-app/watashi-teijide-kaerimasu_1_4.mp3')
Qa.create(:question =>'お', :answer =>'o', :soundfile =>'https://s3.us-east-2.amazonaws.com/vocabrary-app/watashi-teijide-kaerimasu_1_5.mp3')
